apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cyberplace-order-ms
  name: cyberplace-order-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cyberplace-order-ms
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cyberplace-order-ms
    spec:
      containers:
        - env:
            - name: DATABASE_IP
              value: 35.226.229.122
          image: dgonzalezo06/order_ms
          name: cyberplace-order-ms
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
