apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cyberplace-product-management-ms
  name: cyberplace-product-management-ms
spec:
  # type: LoadBalancer
  ports:
    - name: "3333"
      port: 3333
      targetPort: 3333
  selector:
    io.kompose.service: cyberplace-product-management-ms
status:
  loadBalancer: {}
