apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cyberplace-product-search-ms
  name: cyberplace-product-search-ms
spec:
  #type: LoadBalancer
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
  selector:
    io.kompose.service: cyberplace-product-search-ms
status:
  loadBalancer: {}
