apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: product-purchase-ms
  name: product-purchase-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-purchase-ms
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: product-purchase-ms
    spec:
      containers:
        - image: jrozou/cp-pc:latest
          name: product-purchase-ms
          ports:
            - containerPort: 3030
          resources: {}
      restartPolicy: Always
status: {}
